services:
  web-server:
    build: ./web-server
    container_name: web-server
    ports:
      - 84:8081
    networks:
      - sd-net
    volumes:
      - ./web-server:/usr/src/app

networks:
  sd-net:
    name: sd-network
    driver: bridge